Repository Dae-Hwa/airbnb, pull requests merged in 2021-06, with the labels that each got.

#52 [FE] 인원 모달 구현
  FE/fe-airbnb/src/components/MinusButton.tsx
  FE/fe-airbnb/src/components/PlusButton.tsx
  FE/fe-airbnb/src/components/calendar/Day.tsx
  FE/fe-airbnb/src/components/headcount/Counter.tsx
  FE/fe-airbnb/src/components/headcount/HeadCount.tsx
  FE/fe-airbnb/src/components/headcount/HeadCountModal.tsx
  FE/fe-airbnb/src/components/headcount/HeadCountTypes.tsx
  FE/fe-airbnb/src/components/searchBar/SearchBar.tsx
  FE/fe-airbnb/src/components/searchBar/searchBarTypes.ts
  FE/fe-airbnb/src/icon/minus-circle.svg
  FE/fe-airbnb/src/icon/plus-circle-disabled.svg
  FE/fe-airbnb/src/icon/plus-circle.svg
Labels: FE, feature

#58 [FE] 요금 모달 UI 레이아웃, 슬라이더
  FE/fe-airbnb/public/pause-circle.svg
  FE/fe-airbnb/src/components/price/PriceChart.tsx
  FE/fe-airbnb/src/components/price/PriceModal.tsx
  FE/fe-airbnb/src/components/price/RangeSlider.jsx
  FE/fe-airbnb/src/components/price/sampleData.ts
  FE/fe-airbnb/src/icon/pause-circle.svg
Labels: FE, feature

#60 [FE] 요금 모달 state를 SearchBar로 끌어올림, 라우팅 처리
  FE/fe-airbnb/package-lock.json
  FE/fe-airbnb/package.json
  FE/fe-airbnb/src/App.tsx
  FE/fe-airbnb/src/components/SearchButton.jsx
  FE/fe-airbnb/src/components/pages/MainPage.tsx
  FE/fe-airbnb/src/components/pages/ReservationPage.tsx
  FE/fe-airbnb/src/components/price/PriceModal.tsx
  FE/fe-airbnb/src/components/price/RangeSlider.jsx
  FE/fe-airbnb/src/components/searchBar/SearchBar.tsx
  FE/fe-airbnb/src/components/searchBar/searchBarTypes.ts
  FE/fe-airbnb/yarn.lock
Labels: BE

#67 [BE] 숙소 도메인
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationController.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationDTO.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationDTOBuilder.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationDetailResponse.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationDetailResponseBuilder.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationRequest.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationRequestBuilder.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationReservationInfo.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationReservationInfoBuilder.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationResponseBuilder.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/Accommodation.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/AccommodationBuilder.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/AccommodationOption.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/AccommodationOptionBuilder.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/AccommodationTaxPolicy.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/CleaningFeePolicy.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/DiscountPolicy.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/Price.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/PricePolicies.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/PricePolicy.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/PriceUtils.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/ServiceFeePolicy.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/WeekdayDiscountPolicy.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/Weekdays.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/repository/AccommodationRepository.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/service/AccommodationService.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/service/AccommodationServiceImpl.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/service/AccommodationServiceMockup.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/AccommodationDTODummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/AccommodationDummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/AccommodationHostDummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/AccommodationOptionDummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/AccommodationPriceStatsDummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/AccommodationReservationInfoDummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/AccommodationResponseDummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/ReservationDTODummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/ReservationDetailDummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/WishlistItemDTODummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/utils/DummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/reservation/controller/ReservationController.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/reservation/domain/Reservation.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/reservation/domain/ReservationDetail.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/reservation/domain/ReservationDetailBuilder.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/wishlist/WishlistController.java
  BE/airbnb-be/src/test/java/com/codesquad/airbnb/accommodation/controller/AccommodationControllerTest.java
  BE/airbnb-be/src/test/java/com/codesquad/airbnb/accommodation/domain/price/WeekdaysTest.java
  BE/airbnb-be/src/test/java/com/codesquad/airbnb/accommodation/service/AccommodationServiceImplTest.java
  BE/airbnb-be/src/test/java/com/codesquad/airbnb/reservation/controller/ReservationControllerTest.java
  BE/airbnb-be/src/test/java/com/codesquad/airbnb/wishlist/WishlistControllerTest.java
Labels: BE

#68 [iOS] 숙박 리스트 화면
  IOS/airbnb/airbnb.xcodeproj/project.pbxproj
  IOS/airbnb/airbnb/AccommodationConditions/AccommodationConditionViewController.swift
  IOS/airbnb/airbnb/Assets.xcassets/CalendarSelection.colorset/Contents.json
  IOS/airbnb/airbnb/Assets.xcassets/Graph.colorset/Contents.json
  IOS/airbnb/airbnb/Info.plist
  IOS/airbnb/airbnb/Main/AccommodationList/Model/AccommodationCard.swift
  IOS/airbnb/airbnb/Main/AccommodationList/Model/AccommodationDTO.swift
  IOS/airbnb/airbnb/Main/AccommodationList/View/AccommodationCollectionViewCell.swift
  IOS/airbnb/airbnb/Main/AccommodationList/ViewController/AccommodationCollectionViewDataSource.swift
  IOS/airbnb/airbnb/Main/AccommodationList/ViewController/AccommodationListViewController.swift
  IOS/airbnb/airbnb/Main/Home/UseCase/HeroImageUseCase.swift
  IOS/airbnb/airbnb/Main/Home/UseCase/ImageLoadUseCase.swift
  IOS/airbnb/airbnb/Main/Home/ViewController/HomeViewController.swift
  IOS/airbnb/airbnb/Main/Home/ViewModel/HomeViewModel.swift
  IOS/airbnb/airbnb/Network/AlamofireNetworkManager.swift
  IOS/airbnb/airbnb/Network/Fake/FakeNetworkManager.swift
  IOS/airbnb/airbnb/Network/NetworkManagable.swift
  iOS/airbnb/airbnb/AccommodationConditions/BudgetSelect/View/BudgetGraphView.swift
  iOS/airbnb/airbnb/AccommodationConditions/BudgetSelect/ViewController/BudgetViewController.swift
  iOS/airbnb/airbnb/AccommodationConditions/BudgetSelect/ViewModel/BudgetViewModel.swift
  iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/View/CalendarCollectionViewCell.swift
  iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/ViewController/CalendarViewController.swift
  iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/ViewModel/CalendarViewModel.swift
  iOS/airbnb/airbnb/AccommodationConditions/CommonModels/ConditionManager.swift
  iOS/airbnb/airbnb/AccommodationConditions/CommonModels/Period.swift
  iOS/airbnb/airbnb/AccommodationConditions/LocationSearch/UseCase/PopularLocationUseCase.swift
  iOS/airbnb/airbnb/AccommodationConditions/LocationSearch/UseCase/SearchResultUseCase.swift
  iOS/airbnb/airbnb/CommonInterfaces/AnySearchConditionHandleModel.swift
  iOS/airbnb/airbnb/CommonInterfaces/SearchConditionHandleModel.swift
  iOS/airbnb/airbnb/DIContainer/HomeDIContainer.swift
  iOS/airbnb/airbnb/Factory/DateFormatter.swift
Labels: UI, feature, iOS

#70 [FE] 검색 결과로 숙소 리스트 표시
  FE/fe-airbnb/package.json
  FE/fe-airbnb/src/App.tsx
  FE/fe-airbnb/src/HotelListDataType.ts
  FE/fe-airbnb/src/components/SearchButton.jsx
  FE/fe-airbnb/src/components/hotelList/HotelInfo.tsx
  FE/fe-airbnb/src/components/hotelList/HotelInfoList.tsx
  FE/fe-airbnb/src/components/hotelList/hotelInfoTypes.ts
  FE/fe-airbnb/src/components/pages/ReservationPage.tsx
  FE/fe-airbnb/src/components/searchBar/SearchBar.tsx
  FE/fe-airbnb/src/components/searchBar/searchBarTypes.ts
  FE/fe-airbnb/yarn.lock
Labels: FE, feature

#72 [FE] 화면에 지도 표시, 좌표 목데이터로 마커 표시
  FE/fe-airbnb/.env
  FE/fe-airbnb/.gitignore
  FE/fe-airbnb/package.json
  FE/fe-airbnb/src/components/hotelList/HotelInfo.tsx
  FE/fe-airbnb/src/components/hotelList/HotelInfoList.tsx
  FE/fe-airbnb/src/components/map/Map.tsx
  FE/fe-airbnb/src/components/map/mockupCoordinates.js
  FE/fe-airbnb/src/components/pages/ReservationPage.tsx
  FE/fe-airbnb/yarn.lock
Labels: FE, feature
